### ISSUE TITLE
Accept *only* a comparator function as config

### ISSUE THREAD

**Issue by phated** [pgilad/gulp-sort#1]
Would be nice to be able to just pass your comparator as `sort(comparator)` instead of as an object.

**Comment by pgilad** [comment]
Good idea, done!

**Comment by phated** [comment]
awesome.  thanks for the quick response.  we are considering recommending this module in gulp docs for alphabetical sorting of files.

**Comment by pgilad** [comment]
Delighted!! Let me know what needs to be improved/changed. I just sketched this module because I needed it but it seems to do the job pretty well.
