### ISSUE TITLE
Allow stable sorting

### ISSUE THREAD

**Issue by mgol** [pgilad/gulp-sort#3]
This plugin currently relies on `Array#sort` which is unstable. I'd like to provide my own sorting function as I need the stable sort, something like the [stable](https://www.npmjs.com/package/stable) npm package. Unfortunately, this is currently impossible here as I can only pass a comparator function.

**Comment by pgilad** [comment]
Great idea, PR happily received!

**Comment by pgilad** [comment]
Enjoy :smile:

**Comment by mgol** [comment]
Thanks! :)

## 

Michał Gołębiowski
